services:
   redis:
     image: redislabs/redismod
     container_name: redis

   flask:
        build: .
        container_name: flask
        ports:
            - "5000:5000"
        depends_on:
            - redis