services:
   redis:
     image: redislabs/redismod
     container_name: redis

   flask:
        build: .
        image: flasklab1-flask:latest
        container_name: flask
        ports:
            - "5000:5000"
        depends_on:
            - redis